---

- hosts: "all"
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: install git package
    apt:
      name: git
      state: latest
 
  - name: install vim package
    apt:
      name: vim
      state: latest

  - name: install neofetch package
    apt:
      name: neofetch
      state: latest

 
