---

- hosts: "all"
  become: true
  tasks:

  - name: install git, vim, and neofetch packages
    package:
      name: 
        - "{{ git_package }}"
        - "{{ vim_package }}"
        - "{{ neofetch_package }}"
      state: latest
      update_cache: yes

