---

- hosts: "all"
  become: true
  pre_tasks:

  - name: install updates (debian-based)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  tasks:

  - name: install git, vim, and neofetch packages (debian-based)
    apt:
      name: 
        - git
        - vim
        - neofetch
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

- hosts: docker
  become: true
  tasks:

    - name: install nextcloud prerequisites
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: add docker gpg key
      script: scripts/add-docker-gpg-key
      when: ansible_distribution == "Ubuntu"
      
    - name: setup docker repository
      script: scripts/setup-docker-repository
      when: ansible_distribution == "Ubuntu"

    - name: install docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
