---

- hosts: "all"
  become: true
  pre_tasks:

  - name: install updates (debian-based)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  tasks:

  - name: install git, vim, and neofetch packages (debian-based)
    apt:
      name: 
        - git
        - vim
        - neofetch
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

- hosts: docker
  become: true
  tasks:

    - name: install nextcloud prerequisites
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: add docker gpg key
      script: scripts/add-docker-gpg-key
      when: ansible_distribution == "Ubuntu"
      
    - name: setup docker repository
      script: scripts/setup-docker-repository
      when: ansible_distribution == "Ubuntu"

    - name: install docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: media_share
  become: true
  tasks:

    - name: install cifs-utils
      apt: 
        name: cifs-utils
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: make sure /mnt/share directory exists 
      file:
        path: "/mnt/share"
        state: directory
      when: ansible_distribution == "Ubuntu"

    - name: add smb share to /etc/fstab
      blockinfile:
        path: /etc/fstab
        block: |
          //10.0.0.3/jellyfin /mnt/share cifs credentials=/home/thetiiiim/.smbcredentials,uid=thetiiiim,gid=thetiiiim,file_mode=0775,dir_mode=0775,noauto,x-systemd.automount,x-systemd.device-timeout=10,user 0 0
      when: ansible_distribution == "Ubuntu"


    - name: copy smb share credentials to host
      copy:
        src: files/smbcredentials
        dest: /home/thetiiiim/.smbcredentials
        owner: thetiiiim
        group: thetiiiim
        mode: "0600"
      when: ansible_distribution == "Ubuntu"

    - name: mount smb share to destination
      shell: mountpoint -q /mnt/share || mount /mnt/share
      when: ansible_distribution == "Ubuntu"

