---

- hosts: "all"
  become: true
  pre_tasks:

  - name: install updates (debian-based)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  tasks:

  - name: install git, vim, and neofetch packages (debian-based)
    apt:
      name: 
        - git
        - vim
        - neofetch
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]
